---
# https://prettier.io/docs/en/options.html

# specify correct parser
parser: babel
filepath: ''

# main settings
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
qutoeProps: as-needed
traillingCommma: all
bracketSpacing: true
jsxBracketSampleLine: false
jsxSingleQuote: false
arrowParens: avoid
endOfLine: lf

# process always
requirePragma: false
insertPragma: false

overrides:
  - files: "*.json"
    options:
      parser: json
  - files:
      - "*.md"
      - "*.markdown"
    options:
      parser: markdown
  - files:
      - "*.ts"
      - "*.tsx"
    options:
      parser: typescript
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      parser: yaml
